# Generated by Django 3.2.2 on 2021-06-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_feedback_happy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='happy',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=3),
        ),
    ]
