# Generated by Django 3.2.2 on 2021-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_feedback_happy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='happy',
            field=models.BooleanField(),
        ),
    ]
